// Definition of subscription constants.
module.exports = {
  COLUMN_ADDED: "COLUMN_ADDED",
  CARD_ADDED: "CARD_ADDED",
  ON_COLUMN_POSITION_CHANGE: "ON_COLUMN_POSITION_CHANGE",
  ON_CARD_POSITION_CHANGE: "ON_CARD_POSITION_CHANGE",
};
